//using System;
/// < summary >
/// TryCatchFinally class is used to demonstrate how to use try , catch and finally blocks to handle exceptions
/// </summary>
//public class TryCatchFinally
//{
//    #region Public Methods

//    / <summary>
//    / TestFinally is used to demonstrate use of finally keyword
//    / </summary>
//    static void TestFinally()
//    {
//        string path = @"C:\Users\KRINSHI\OneDrive\Documents\RKIT\C#\FileHandling\FileHandling\text\file1.txt";
//        try
//        {
//            File.AppendAllText(path, "Appended Line One.\nAppended Line Two.");
//        }
//        catch (IOException ex)
//        {
//            Console.WriteLine(ex.Message.ToString());
//        }
//        finally
//        {
//            Console.WriteLine("Close filestreams and databases if any.");
//        }
//    }
//    public static void Main()
//    {
//        TestFinally();
//    }

//    #endregion
//}
